### PR TITLE
Optional features

### PR DESCRIPTION
**Pull request by pizzamig**
Add support to features, to be able to select only the needed format

### CODE REVIEW

**Review by AlexanderThaller — APPROVED** [review]

**Comment by AlexanderThaller** [comment]
Probably the readme can also be updated but the readme is pretty bad at the moment anyway.

**Comment by pizzamig** [comment]
yeah, I didn't prepare any documentation. I wanted to have your :+1: before to proceed :sweat_smile: 
With features, the documentation is crucial

**Comment by AlexanderThaller** [comment]
Yeah the feature documentation needs to still get better at least you can see them in doc.rs now :D https://docs.rs/crate/prometheus_exporter/0.8.2/features

**Comment by AlexanderThaller** [comment]
You can merge it if you want.

**Comment by pizzamig** [comment]
As external contributor, I cannot merge or run the workflow..

**Comment by AlexanderThaller** [comment]
As removing the `serde_json` feature from the default this is a breaking change gonna put it into the `0.2.0` milestone.

**Pull request merged**
